'use client';

import { useState } from 'react';
import { Language, getTranslation } from '@/lib/translations';

interface Summary {
  report_id: string;
  generated_at: string;
  findings: string[];
  key_questions_answered: string[];
  recommendations: string[];
  follow_up_actions: string[];
}

interface SessionSummaryProps {
  summary: Summary | null;
  patientName: string;
  language: Language;
  onClose: () => void;
}

export default function SessionSummary({
  summary,
  patientName,
  language,
  onClose,
}: SessionSummaryProps) {
  const [isDownloading, setIsDownloading] = useState(false);

  if (!summary) return null;

  const handleDownload = () => {
    setIsDownloading(true);
    try {
      const summaryText = `
TELEHEALTH INSIGHT COMPANION - SESSION SUMMARY
===============================================

Patient: ${patientName}
Generated: ${new Date(summary.generated_at).toLocaleString()}
Report ID: ${summary.report_id}

KEY FINDINGS:
${summary.findings.map((f, i) => `${i + 1}. ${f}`).join('\n')}

RECOMMENDATIONS:
${summary.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

FOLLOW-UP ACTIONS:
${summary.follow_up_actions.map((a, i) => `${i + 1}. ${a}`).join('\n')}

${summary.key_questions_answered.length > 0 ? `QUESTIONS ANSWERED:\n${summary.key_questions_answered.map((q, i) => `${i + 1}. ${q}`).join('\n')}` : ''}

===============================================
This summary was generated by the Telehealth Insight Companion.
Please consult with your healthcare provider for medical advice.
      `.trim();

      const blob = new Blob([summaryText], { type: 'text/plain' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `summary_${summary.report_id}.txt`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-gradient-to-br from-slate-800 to-slate-900 rounded-lg border border-slate-700 max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        <div className="sticky top-0 bg-slate-900 border-b border-slate-700 p-6 flex justify-between items-center">
          <h2 className="text-2xl font-bold text-white">
            {getTranslation(language, 'summary')}
          </h2>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-white transition-colors"
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <div className="p-6 space-y-6">
          <div>
            <p className="text-slate-400 text-sm">
              <span className="font-semibold">{getTranslation(language, 'patient_name')}:</span> {patientName}
            </p>
            <p className="text-slate-400 text-sm">
              <span className="font-semibold">Generated:</span> {new Date(summary.generated_at).toLocaleString()}
            </p>
          </div>

          {summary.findings.length > 0 && (
            <div>
              <h3 className="text-lg font-semibold text-blue-400 mb-3">
                {getTranslation(language, 'findings')}
              </h3>
              <ul className="space-y-2">
                {summary.findings.map((finding, index) => (
                  <li key={index} className="text-slate-300 flex gap-3">
                    <span className="text-blue-400 font-semibold min-w-fit">{index + 1}.</span>
                    <span>{finding}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {summary.recommendations.length > 0 && (
            <div>
              <h3 className="text-lg font-semibold text-green-400 mb-3">
                {getTranslation(language, 'recommendations')}
              </h3>
              <ul className="space-y-2">
                {summary.recommendations.map((rec, index) => (
                  <li key={index} className="text-slate-300 flex gap-3">
                    <span className="text-green-400 font-semibold min-w-fit">{index + 1}.</span>
                    <span>{rec}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {summary.follow_up_actions.length > 0 && (
            <div>
              <h3 className="text-lg font-semibold text-amber-400 mb-3">
                {getTranslation(language, 'follow_up')}
              </h3>
              <ul className="space-y-2">
                {summary.follow_up_actions.map((action, index) => (
                  <li key={index} className="text-slate-300 flex gap-3">
                    <span className="text-amber-400 font-semibold min-w-fit">{index + 1}.</span>
                    <span>{action}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {summary.key_questions_answered.length > 0 && (
            <div>
              <h3 className="text-lg font-semibold text-purple-400 mb-3">Questions Discussed</h3>
              <ul className="space-y-2">
                {summary.key_questions_answered.map((q, index) => (
                  <li key={index} className="text-slate-300 flex gap-3">
                    <span className="text-purple-400 font-semibold min-w-fit">{index + 1}.</span>
                    <span>{q}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>

        <div className="sticky bottom-0 bg-slate-900 border-t border-slate-700 p-6 flex gap-3">
          <button
            onClick={handleDownload}
            disabled={isDownloading}
            className="flex-1 bg-blue-600 hover:bg-blue-700 disabled:bg-slate-600 text-white font-semibold py-2 px-4 rounded-lg transition-colors"
          >
            {isDownloading ? 'Downloading...' : getTranslation(language, 'download_summary')}
          </button>
          <button
            onClick={onClose}
            className="flex-1 bg-slate-700 hover:bg-slate-600 text-white font-semibold py-2 px-4 rounded-lg transition-colors"
          >
            {getTranslation(language, 'close')}
          </button>
        </div>
      </div>
    </div>
  );
}
